### ISSUE TITLE
点餐界面

### ISSUE THREAD

**Issue by rongjielong** [CodingGarfield/CookingOrder#10]
点餐界面

**Comment by GreyZeng** [comment]
注意合理分配好3个Milestone的任务，你们目前只有一个milestone吗？
@rongjielong @Ttbabys @IAMWicker @zhangwofengyuhuodenanren @wenhong11

**Comment by rongjielong** [comment]
还在规划剩余的两个 @GreyZeng

**Comment by rongjielong** [comment]
还在规划剩余的两个 @GreyZeng
